In [15]:
# !pip install konlpy
# !pip install gensim
# !pip install fasttext
# import fasttext

In [2]:
import keras

import tensorflow
print(keras.__version__)
print(tensorflow.__version__)

Using TensorFlow backend.


2.3.1
1.13.2


In [2]:
import tensorboard

In [4]:
print(tensorboard.__version__)

2.0.0


In [3]:
from konlpy.tag import Okt
from gensim.models import Word2Vec
# from gensim.models import FastText
import pandas as pd
import re
import numpy as np
from sklearn.preprocessing import StandardScaler

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)


In [4]:
import math
def delete_emoji(sentence):
    try:
        hangul = re.compile('[^ ㄱ-ㅣ가-힣A-Za-z0-9]+') # 한글과 띄어쓰기를 제외한 모든 글자
        result = hangul.sub('', sentence) # 한글과 띄어쓰기를 제외한 모든 부분을 제거
#         result.replace('\n',' ')
        return result
    except:
        print('test')
        return ' '



In [51]:
# df1 = pd.read_csv('title_label.csv')
df2 = pd.read_csv('./data/url_label1.csv')

In [6]:

%%time
import urllib
from bs4 import BeautifulSoup
title=[]
for idx, url in enumerate(list(df2['url'])):
    if idx%50==0:
        print(idx)
    target_html = 'https://www.youtube.com{}'.format(url)
    html = urllib.request.urlopen(target_html).read()
    soup = BeautifulSoup(html, 'html.parser')
    title.append(soup.find('title').text[:-10])

NameError: name 'df2' is not defined

In [ ]:
df2['title']=title

In [3]:
df2.to_csv('title_label1.csv',encoding='utf-8',index=False)

NameError: name 'df2' is not defined

In [5]:
df1 = pd.read_csv('data/title_label1.csv')
df2 = pd.read_csv('data/title_label2.csv')

In [6]:
df=pd.concat([df1,df2])

In [8]:
print(df.shape)
df.drop_duplicates(inplace=True)
print(df.shape)

(1761, 3)
(1725, 3)


In [17]:
remove=[]
for idx, i in enumerate(list(df['title'])[:100]):
    subject = list(df['subject'])[idx]
    if subject==1:
        s='게임'
    elif subject==2:
        s='노래'
    elif subject==3:
        s='IT'
    elif subject==4:
        s='영화'
    print("[{}] {}".format(s,i))
    r = input()
    if r=='1':
        remove.append(1)
    else:
        remove.append(0)

[게임] 너무 쎄서 같은팀도 때리고싶은데 참습니다...
d


KeyboardInterrupt: 

In [7]:
df_test = df.loc[ ((df['subject'] == 1) | (df['subject']==2))]

In [9]:
%%time
tagger = Okt()
sentences = list(df['title'])
sentences = [delete_emoji(sentence) for sentence in sentences]
sentences_Okt = []
for idx, sentence in enumerate(sentences):
    sen_okt = tagger.morphs(sentence)
    sentences_Okt.append(sen_okt)




C:\Users\JeongMyeong\Anaconda3\lib\site-packages\jpype\_core.py:210: UserWarning: 
-------------------------------------------------------------------------------
Deprecated: convertStrings was not specified when starting the JVM. The default
behavior in JPype will be False starting in JPype 0.8. The recommended setting
for new code is convertStrings=False.  The legacy value of True was assumed for
this session. If you are a user of an application that reported this warning,
please file a ticket with the developer.
-------------------------------------------------------------------------------

  """)


Wall time: 4.72 s


In [28]:
df.iloc[1171]

url                             /watch?v=mNByooKR4J8
subject                                            2
title      [멜론차트] 2019년 10월 3주차 KPOP 실시간 최신가요 멜론차트!!
Name: 239, dtype: object

In [12]:
# word2vec_model = Word2Vec(sentences=sentences_Okt, size=300, window=4, min_count=1, sg=1)

In [19]:
from gensim import models
# models.fast
# cap_path = datapath("C:/Users/JeongMyeong/Desktop/word-embeddings/fasttext/fasttext.bin")
fb_model = models.fasttext.load_facebook_model('C:/Users/JeongMyeong/Desktop/word-embeddings/fasttext/fasttext.bin')

In [11]:
fb_model.wv.

{'1': <gensim.models.keyedvectors.Vocab at 0x1bf8cba7cc0>,
 '.': <gensim.models.keyedvectors.Vocab at 0x1bf8cba7cf8>,
 '0': <gensim.models.keyedvectors.Vocab at 0x1bf8cba7d30>,
 '2': <gensim.models.keyedvectors.Vocab at 0x1bf8cba7d68>,
 'ㅇㅢ-': <gensim.models.keyedvectors.Vocab at 0x1bf8cba7da0>,
 ',': <gensim.models.keyedvectors.Vocab at 0x1bf8cba7dd8>,
 'ㅇㅣ-': <gensim.models.keyedvectors.Vocab at 0x1bf8cba7e10>,
 'ㄴㅡㄴ': <gensim.models.keyedvectors.Vocab at 0x1bf8cba7e48>,
 'ㄷㅏ-': <gensim.models.keyedvectors.Vocab at 0x1bf8cba7e80>,
 ')': <gensim.models.keyedvectors.Vocab at 0x1bf8cba7eb8>,
 '(': <gensim.models.keyedvectors.Vocab at 0x1bf8cba7ef0>,
 '9': <gensim.models.keyedvectors.Vocab at 0x1bf8cba7f28>,
 'ㄴㅕㄴ': <gensim.models.keyedvectors.Vocab at 0x1bf8cba7f60>,
 'ㅇㅔ-': <gensim.models.keyedvectors.Vocab at 0x1bf8cba7f98>,
 'ㅇㅡㄹ': <gensim.models.keyedvectors.Vocab at 0x1bf8cba7fd0>,
 'ㅎㅏ-': <gensim.models.keyedvectors.Vocab at 0x1bf8cbae048>,
 '3': <gensim.models.keyedvectors.Vocab 

In [10]:
word2vec_model = Word2Vec.load('C:/Users/JeongMyeong/Desktop/word-embeddings/word2vec/word2vec')

In [18]:
cnt=0
for i in word2vec_model.wv.vocab:
    cnt+=1

In [19]:
cnt

358043

In [20]:
from sklearn.externals.joblib import dump, load
def vectorize(model, sentences):
  
    result = []
    for idx, sentence in enumerate(sentences):
        tmp = []
        for word in sentence:
            try:
                tmp.append(model.wv.word_vec(word))
            except:
                pass
        if tmp==[]:
            print(sentence)
            result.append(np.zeros((model.wv.vector_size, ),dtype='float32'))
        else:
            result.append(sum(tmp)/len(tmp)) 
    return np.array(result)


def scaler_transform(train, test): # , valid, test):
#     scaler = StandardScaler()
    scaler = load('std_scaler.bin')
    train_scale = scaler.fit_transform(train)
#     valid_scale = scaler.transform(valid)
    test_scale = scaler.transform(test)
#     dump(scaler, 'std_scaler.bin', compress=True)
    return train_scale, test_scale # valid_scale, test_scale

def score(prediction, label):
    prediction = [1 if p>0.5 else 0 for p in prediction]
    return accuracy_score(prediction, label)

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(sentences_Okt, df['subject'], test_size=0.1, random_state=42)
X_train_vec = vectorize(fb_model, X_train)
# X_valid_vec = vectorize(word2vec_model, X_valid_Okt)
X_test_vec = vectorize(fb_model, X_test)

In [27]:
X_train_scale, X_test_scale = scaler_transform(X_train_vec, X_test_vec)

In [28]:
dim = fb_model.wv.vector_size
vocab = len(fb_model.wv.vocab)

In [29]:
import keras
y_train_category = [i-1 for i in y_train]
y_test_category = [i-1 for i in y_test]
y_train_category = keras.utils.np_utils.to_categorical(y_train_category, num_classes=4)
y_test_category = keras.utils.np_utils.to_categorical(y_test_category, num_classes=4)

X_train_scale, X_valid_scale, y_train_category, y_valid_category = train_test_split(X_train_scale, y_train_category, test_size=0.1, random_state=42)

In [30]:
import warnings
warnings.filterwarnings('ignore')

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from keras.models import Model 
from keras.layers import Flatten, Dropout,Conv2D, concatenate,Conv1D, MaxPooling1D,Dense, Embedding, LSTM, Input
from sklearn.preprocessing import StandardScaler
from keras.callbacks import EarlyStopping
# import tensorflow as tf
# run_opts = tf.RunOptions(report_tensor_allocations_upon_oom = True)


input_sentence = Input(shape=(dim,))
emb = Embedding(vocab+1, 32, input_length=dim)(input_sentence)
drop = Dropout(0.5)(emb)
conv = Conv1D(3,3, padding='valid', activation='relu')(emb)
maxpool = MaxPooling1D(pool_size=1)(conv)
flat = Flatten()(maxpool)
hidden = Dense(16, activation='relu')(flat)
drop = Dropout(0.5)(hidden)
output = Dense(4, activation='softmax')(hidden)
cnn_model = Model(input_sentence, output)
cnn_model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])#, options = run_opts)
early_stopping  = EarlyStopping()


In [31]:
cnn_model.fit(X_train_scale,y_train_category, 
            batch_size=64, 
            epochs=30, 
            callbacks=[early_stopping],
            validation_data=(X_valid_scale, y_valid_category)
           )

Train on 1396 samples, validate on 156 samples
Epoch 1/30
1396/1396 [==============================] - 0s 259us/step - loss: 1.3792 - accuracy: 0.3216 - val_loss: 1.3631 - val_accuracy: 0.3910
Epoch 2/30
1396/1396 [==============================] - 0s 123us/step - loss: 1.3101 - accuracy: 0.4721 - val_loss: 1.2387 - val_accuracy: 0.5321
Epoch 3/30
1396/1396 [==============================] - 0s 121us/step - loss: 1.0467 - accuracy: 0.7013 - val_loss: 0.8580 - val_accuracy: 0.7949
Epoch 4/30
1396/1396 [==============================] - 0s 119us/step - loss: 0.6866 - accuracy: 0.7837 - val_loss: 0.6920 - val_accuracy: 0.8141
Epoch 5/30
1396/1396 [==============================] - 0s 119us/step - loss: 0.5427 - accuracy: 0.8195 - val_loss: 0.6606 - val_accuracy: 0.8077
Epoch 6/30
1396/1396 [==============================] - 0s 121us/step - loss: 0.4799 - accuracy: 0.8331 - val_loss: 0.6289 - val_accuracy: 0.8397
Epoch 7/30
1396/1396 [==============================] - 0s 120us/step - loss:

In [32]:
cnn_model.save('newmodel2.h5')

In [70]:
predict = cnn_model.predict(X_test_scale)

In [71]:
prediction=[]
for i in range(len(X_test_scale)):
    tt = list(predict[i])
    prediction.append(tt.index(max(tt)))
    

In [72]:
prediction = keras.utils.np_utils.to_categorical(prediction, num_classes=4)

In [73]:
accuracy_score(prediction, y_test_category)

0.8418079096045198

In [74]:
y_test_category[0:10]

array([[1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.]], dtype=float32)

In [48]:
print(multilabel_confusion_matrix(prediction,y_test_category))

[[[121   7]
  [ 14  35]]

 [[132  10]
  [  1  34]]

 [[117   7]
  [  7  46]]

 [[131   6]
  [  8  32]]]


In [46]:
print(confusion_matrix(y_valid_category, prediction))

ValueError: Found input variables with inconsistent numbers of samples: [159, 177]

array([0., 1., 0., 0.], dtype=float32)

In [332]:
cnt=0
for idx, (predict, label) in enumerate(zip(prediction, y_test_category)):
    if list(predict) != list(label):
        print(X_test[idx], predict, label)
        cnt+=1
print(cnt, len(y_test_category))
print(cnt/len(y_test_category))

['TV', '문학관', '39', '화', '김', '약국', '의', '딸', '들', 'Kims', 'Daughters', '19820424'] [0. 0. 0. 1.] [0. 0. 1. 0.]
['충', '동', '적', '아이폰', '11', '프로', '실버', '언박싱', '개인', '적', '인', '컬러', '선호', '도', '순위'] [1. 0. 0. 0.] [0. 0. 1. 0.]
['악마', '의', '라인', '전', '누구', '나', '의문', '을', '가질', '수', '밖에', '없는', 'CS', '차이', '웅플'] [0. 0. 0. 1.] [1. 0. 0. 0.]
['이', '모든', '게', '3일', '만에', '일어난', '일', '연애', '웹툰', '1', '둘', '이', '어떻게', '만났어요'] [0. 0. 0. 1.] [1. 0. 0. 0.]
['기름', '통', '폭발', '업데이트', '되고나서', '믿을', '사람', '이', '없어졌다', '나도', '믿지마', '셈', 'ㅋㅋ', '배그', '모바일'] [0. 0. 1. 0.] [1. 0. 0. 0.]
['180930', '아이유', 'IU', '좋은', '날', '너', '랑', '나', '금요일', '에만', '나', '요', '너', '의', '의미', '삼성', '카드', '홀', '가분', '마켓', '4', 'K', '직캠', 'by', '비몽'] [1. 0. 0. 0.] [0. 1. 0. 0.]
['우리', '결혼', '준비', '해', '요', 'EP', '04', 'ㅣ', '웨딩드레스', '입은', '여자친구', '보고', '눈물', '핑', '돌았습니다', '1', '부'] [0. 0. 0. 1.] [0. 1. 0. 0.]
['본인', '도', '놀라', '버린', '미친딜', '이', '거', '왜', '이렇게', '쎄요', '레전드'] [0. 0. 0. 1.] [1. 0. 0. 0.]
['킴성태', '의', '2년', '전',

In [36]:
from sklearn.metrics import multilabel_confusion_matrix

In [33]:
from tensorflow.python.client import device_lib

print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 12027243782438396712
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 6600259666
locality {
  bus_id: 1
  links {
  }
}
incarnation: 8544564182979099928
physical_device_desc: "device: 0, name: GeForce RTX 2070 SUPER, pci bus id: 0000:07:00.0, compute capability: 7.5"
]


In [ ]:
import sys
from PyQt5.QtWidgets import QApplication, QWidget, QPushButton, QMainWindow, QDesktopWidget, QMessageBox, QCheckBox, \
    QLineEdit,QListWidgetItem
from pytube import YouTube # !pip install pytube
from PyQt5.QtWidgets import QLabel, QComboBox, QProgressBar, QListWidget,QFileDialog
from PyQt5.QtCore import QThread, pyqtSignal, QFile
import time
import YoutubeCrawl
import processed_classification
import os


class YoutubeDownloader(QWidget):
    def __init__(self):
        super().__init__()
        self.initUI()
        self.Youtube_info = YoutubeCrawl.Youtube()
        self.processed = processed_classification.ProcessSentence()

    def initUI(self):
        self.center()
        self.setGeometry(500, 500, 600, 500)
        ## Button
        self.saveBTN = QPushButton("저장", self)
        self.saveBTN.setGeometry(490, 400, 80,55)
        self.saveBTN.clicked.connect(self.save_cmd)

        self.searchBTN = QPushButton("검색", self)
        self.searchBTN.setGeometry(520, 10, 50, 35)
        self.searchBTN.clicked.connect(self.search_cmd)

        self.dir_pathBTN = QPushButton("폴더", self)
        self.dir_pathBTN.setGeometry(490, 370, 80,30)
        self.dir_pathBTN.clicked.connect(self.path_select)

        self.quality_BTN = QPushButton('해상도 보기',self)
        self.quality_BTN.setGeometry(300,400,80,20)
        self.quality_BTN.clicked.connect(self.quality_add)
        ##
        # Label
        self.path_label = QLabel("경로 : ", self)
        self.path_label.move(50, 370)

        self.quality_label = QLabel("해상도 : ", self)
        self.quality_label.move(50, 400)
        ##
        # TextBox
        self.path_textbox = QLineEdit(self)
        self.path_textbox.setGeometry(90, 370, 365, 20)

        self.search_word_textbox = QLineEdit(self)
        self.search_word_textbox.setGeometry(50,10,420,30)
        ##

        # CheckBox
        self.auto_checkbox = QCheckBox("자동분류", self)
        self.auto_checkbox.move(390, 400)

        # ComboBox
        self.quality_combobox = QComboBox(self)
        self.quality_combobox.setGeometry(90, 400,200,20)


        self.progress = QProgressBar(self)
        self.progress.setGeometry(90, 430, 400, 25)
        self.progress.setMaximum(100)


        self.titleQListWidget = QListWidget(self)
        self.titleQListWidget.setGeometry(50,50,520,300)
        self.titleQListWidget.currentItemChanged.connect(self.get_title)

        self.show()


    def path_select(self):
        self.file_path = str(QFileDialog.getExistingDirectory(self, "Select Directory"))
        self.path_textbox.setText(self.file_path)

    def center(self):
        qr = self.frameGeometry()
        cp = QDesktopWidget().availableGeometry().center()
        qr.moveCenter(cp)
        self.move(qr.topLeft())

    def save_cmd(self):
        self.download_stream = self.streams[self.combos[self.quality_combobox.currentText()]]

        X = self.processed.sent_to_vec(self.download_stream.title)
        print(X)
        # if os.path.isdir("{}/{}".format(self.path_textbox.text(), self.processed.predict(X))) == False:
        #     os.mkdir("{}/{}".format(self.path_textbox.text(), self.processed.predict(X)))
        #
        # self.download_stream.download("{}/{}".format(self.path_textbox.text(), self.processed.predict(X)))

    def search_cmd(self):
        self.progress.setValue(70)
        self.titleQListWidget.clear()
        self.title_href_dict = self.Youtube_info.search(self.search_word_textbox.text())
        self.titleQListWidget.addItems(list(self.title_href_dict.keys()))
        self.progress.setValue(100)

    def get_title(self):
        try: # 리스트에 item을 클릭하고 검색시 알 수 없는 오류. 아마, currentItem이 가르키는 주소값이 변경되어서 그런것으로 의심됨.
            self.select_title = self.titleQListWidget.currentItem().text()
            print(self.select_title)
        except:
            pass

    def progress_function(self,stream, chunk, file_handle, bytes_remaining):
        self.progress.setValue(int((1 - bytes_remaining / self.download_stream.filesize) * 100))


    def quality_add(self):
        self.quality_combobox.clear()
        self.progress.setValue(30)
        try:
            yt = YouTube('https://www.youtube.com'+self.title_href_dict[self.select_title], on_progress_callback=self.progress_function)
        except:
            print('error')
        # 유튜브의 description을 보고 분류.
        self.streams = yt.streams.all()

        self.combos = dict()

        for idx, stream in enumerate(self.streams):
            if 'video/mp4' in stream.mime_type:
                self.combos['{} {} {} {}MB'.format(stream.mime_type, stream.resolution, stream.fps,
                                                     round(stream.filesize / (1024 * 1024)))] = idx

            elif 'audio/mp4' in stream.mime_type:
                self.combos['{} {}'.format(stream.mime_type, stream.abr)] = idx

        self.quality_combobox.addItems(list(self.combos.keys()))
        self.progress.setValue(100)





if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = YoutubeDownloader()
    sys.exit(app.exec_())